import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "@/context/AppProvider";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "MatchUp-Tournament management system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
