import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "@/context/AppProvider";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navber";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MatchUp-Tournament management system",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
          <Toaster />
        </body>
      </AppProvider>
    </html>
  );
}
